### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function Eventviva\imagecreatefrom*

### ISSUE THREAD

**Issue by ibrokemypie** [gumlet/php-image-resize#99]
Hello, trying to us your library but every file fails to resizewith an error like the following, happening with both png and jpeg images
```
[Mon Jan  8 11:15:26 2018] PHP Fatal error:  Uncaught Error: Call to undefined function Eventviva\imagecreatefrompng() in /php/ImageResize.php:112
Stack trace:
#0 /upload.php(48): Eventviva\ImageResize->__construct('/tmp/phpV0fAfB')
#1 {main}
  thrown in /php/ImageResize.php on line 112
[Mon Jan  8 11:15:26 2018] 192.168.1.149:33896 [500]: /upload.php - Uncaught Error: Call to undefined function Eventviva\imagecreatefrompng() in /php/ImageResize.php:112
Stack trace:
#0 /upload.php(48): Eventviva\ImageResize->__construct('/tmp/phpV0fAfB')
#1 {main}
  thrown in /php/ImageResize.php on line 112

```
is this a bug or am I doing something  wrong?

**Comment by adityapatadia** [comment]
Your calling method seems odd. Can you try following?

```php
use \Eventviva\ImageResize;
$image = new ImageResize('image.jpg');
```

**Comment by adityapatadia** [comment]
Closing this due to inactivity. I will open if it still persists.
